# ==========================================================================
# Project:   Todos
# Copyright: @2011 4D Evolution, Inc.
# ==========================================================================

# Add initial buildfile information here
config :all, :required => ["sproutcore/core_foundation", "sproutcore/datastore"], :theme => "sproutcore/empty_theme"

